spring:
  application:
    name: acme-shipping
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true

axon:
  axonserver:
    servers: localhost:8124

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR